event_type_dict = {'CLL':'Container loaded at first POL',
                    'VDT':'Vessel departure from T/S (Transhipment Port)',
                    'VAT':'Vessel arrival at T/S port (Transhipment Port)',
                    'CDT':'Container discharge at T/S port (Transhipment Port)',
                    'VDL':'Vessel departure from first POL (Port of Load)',
                    'CDD':'Container discharge at final POD (Port of Discharge)',
                    'VAD':'Vessel arrival at final POD (Port of Discharge)',
                    'CLT':'Container loaded at T/S port (Transhipment Port)',
                    'UNK':'Unknown',
                    'LTS':'Land transhipment',
                    'BTS':'Barge transhipment',
                    'CEP':'Container empty to shipper',
                    'CPS':'Container pickup at shipper',
                    'CGI':'Container gate in at POL (Port of Load)',
                    'TSD':'Transhipment delay',
                    'CDC':'Container delivery to consignee',
                    'CER':'Container empty return to depot',
                    'CGO':'Container gate out at POD (Port of Discharge)'}