
Shipment_status_dict = {1:'Booked',
                    2:'Collected from Shipper',
                    3:'Not arrived at Port of Load',
                    4:'Waiting at Port of Load',
                    5:'Shipped on board',
                    6:'Underway',
                    7:'Underway to a Transhipment Port (to be added soon)',
                    8:'Arrival at Transhipment Port (to be added soon)',
                    9:'Waiting at Transhipment Port',
                    10:'Shipped on board at Transhipment Port',
                    11:'Arrived at Port or Discharge',
                    12:'Waiting at Destination Port',
                    13:'Left the Destination Port',
                    14:'Shipment Completed'}